# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50041aa4ad3fd0038e8288a6ccfe9dc3f4e970b0d696c726ead3932b9d8c8e4f25c8c15b22f59a0ab0812a1a094a3e6dab6b9db64a9704375a9f4da3c3808def

test:
  secret_key_base: 81477809884bb4d8bd9e5f8dfbb211c23d211180bffd08f6a5f3c77cb545f438c3b65947dd62cec85440a2a889d60be6a784a3e40b2503779fe04ad97b9d29c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
